---
title: "Client Report - [What's in a name?]"
subtitle: "Course DS 250"
author: "[Ana Soto]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
```


## Elevator pitch

_The approach you take to load in your data depends on the type of file its contained within. The method below is a automated and organized way of loading your data. It helps you identify and fix errors in a more proper manner. The format of the 'year' column was not recognize a date, so that had to be changed._

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")

df['year'] = pd.to_datetime(df["year"], format="%Y")

```


## QUESTION 1

__How does your name at your birth year compare to its use historically?__

_The usage of the name Ana was quite popular in the year 1999. My birth year is definetly amongst the three most popular years of its usage. This could definitely explain why I have several cousins whose name is also Ana. The popularity of the name is prominent for about 20 years straight._

```{python}
#| label: Q1 

Ana = df.query("name == 'Ana'")

Ana_chart = px.line(Ana, x='year', y='Total', title='Ana Through Time')

Ana_chart.add_vline(x='1999', line_dash="dash", line_color="orange")

Ana_chart.update_layout(xaxis_title='Year', yaxis_title='Total Count')

Ana_chart.show()

```


## QUESTION 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_If I was talking to a Brittany on the phone, I would guess her age was between 32 and 34 years old. More specifically, I would guess she is 34 years old. Since, the year 1990 is where the usage of the name is at its highest._

```{python}
#| label: Q2

Brittany = df.query("name == 'Brittany'")

Brittany_chart = px.bar(Brittany, x='year', y='Total', title='Brittany Through Time')

Brittany_chart.update_layout(xaxis_title='Year', yaxis_title='Total Count')

Brittany_chart.show()

```


## QUESTION 3

__Mary,Martha,Peter, and Paul are all Christian names. From 1920-2000, compare the name usage of each of the four names. What trends do you notice?__

_If we take a look at the graph, its quite clear that Mary is the most popular name within the timeframe. The most popular year for the name usage is 1950. In second place, for the most popular name,is Paul. The highest peak for the usage of that name is at about 1954. It is interesting to notice that after the name Mary starts decreasing, the name Paul starts increasing in popularity. _

```{python}
#| label: Q3

ChristianNames = (df
        .query("name in ['Mary','Martha', 'Peter', 'Paul']")
        .query("year >= 1920 and year <=2000"))

ChristianNames_chart = px.line(ChristianNames, x='year', y='Total', color = 'name', title='Mary, Martha, Peter and Paul Through Time')

ChristianNames_chart.update_layout(xaxis_title='Year', yaxis_title='Total Count', legend_title=' ')

ChristianNames_chart.show()

```

## QUESTION 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__

_The movie 'Mission: Impossible' debuted in 1996 with Tom Cruise being the main actor. The movie had no effect on the popularity of the name in the following years. In fact, we can see that usage of the name started decreasing.However, its most popular year was 1959._

```{python}
#| label: Q4

Tom= df.query("name == 'Tom'")

Tom_chart = px.line(Tom, x='year', y='Total', title='Tom Through Time')

Tom_chart.add_vline(x='1996', line_dash="dash", line_color="orange")

Tom_chart.update_layout(xaxis_title='Year', yaxis_title='Total Count')

Tom_chart.show()

```

             