project: 
  type: website

website:
  title: "Ana_Soto Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/sotoana/DS-250.git
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Ana_Soto 2023©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/ana-soto-/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      # - text: "DS250 Projects"
      #   file: projects.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Data Cleansing"
        file: cleansing.qmd
      - text: "Data Exploration"
        file: exploration.qmd
      - text: "Story Telling"
        file: story_telling.qmd
      - text: "Machine Learning"
        file: ml.qmd
      - text: "Full Stack"
        file: full_stack.qmd
      - text: "Competition"
        file: competition.qmd
      
  sidebar:
    - title: "Data Cleansing"
      style: "docked"
      background: light
      contents:
        - text: "Data Cleansing"
          file: cleansing.qmd
        - text: "---"
        - text: "Project 1"
          file: Cleansing/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Cleansing/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Cleansing/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Cleansing/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Cleansing/project5.qmd
        - text: "---"
        #continue the pattern if you need more links
        #copy paste from title and keep it indented to sidebar to add additonal sidebar navigation for other pages

format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



