---
layout: cv
---

# Ana Soto

[LinkedIn](https://www.linkedin.com/in/ana-soto-/) | [Gmail](mailto:ana.soto@gmail.com)


## Skills and Qualifications

- Power BI & DAX
- Microsoft SQL Server
- R Studio
- Microsoft Excel
- Data Visualization
- Leadership

## Work Experience

__Data Analyst__  &nbsp;&nbsp;&nbsp; `Sept 2021 -  Present`

Brigham Young University-Idaho

- Developed Power BI and Report builder dashboards/reports for 100+ users
- Conducted frequent data analysis using SQL queries
-   Led and mentored a team of four students in Power BI, SQL and R Studio
- Collaborated on report presentation and analysis with a detail oriented team for analyses during a three month period
- Performed a word cluster analysis to identify top-rated instructor's qualities that will influence on 100+ future online instructors' training


__Library Aide__   &nbsp;&nbsp;&nbsp; `Apr 2021 - Sept 2021`

Brigham Young University - Idaho

- Developed communication skills through interacting with team members and over 30 patrons per day
- Executed various tasks efficiently while maintaining a professional work environment
- Provided prompt assistance to library patrons and addressed inquiries

## Education

__Brigham Young University-Idaho__ &nbsp;&nbsp;&nbsp; `Expected Graduation July 2024`



## Additional Experience

Database Design and Development Project &nbsp;&nbsp;&nbsp; `Apr 2022 - July 2022`

 *Brigham Young University-Idaho*

- Designed a comprehensive database with a proper ERD,relationships,keys, and data types
- Collaborated within a team to ensure a professional project presentation
- Executed various SQL states to populate over eight different tables




<!-- ### Footer

Last updated: May 2013 -->
